services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: kicktime-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "KickTime@12345"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: src/KickTime.API/Dockerfile
    container_name: kicktime-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

volumes:
  sqlserver-data: