@ECHO OFF

SET DBNAME=KickTime
SET SERVER_NAME=9ASM19005
SET USERNAME=sa
SET PASSWORD=Superm@n

ECHO DB_Name = %DBNAME%
call KickTime.bat %DBNAME% %SERVER_NAME% %USERNAME% %PASSWORD%
call KickTime_Seeds.bat %DBNAME% %SERVER_NAME% %USERNAME% %PASSWORD%
PAUSE