USE [$(dbName)]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Roles') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Roles
GO

CREATE TABLE Roles
(
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,

    Name NVARCHAR(50) NOT NULL UNIQUE,

    Description NVARCHAR(200) NULL,

    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),

    UpdatedAt DATETIME2 NULL
);

GO