Use KickTime;

CREATE TABLE Roles
(
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,

    Name NVARCHAR(50) NOT NULL UNIQUE,

    Description NVARCHAR(200) NULL,

    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),

    UpdatedAt DATETIME2 NULL
);