CREATE TABLE Stadiums
(
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,

    Name NVARCHAR(150) NOT NULL,

    Address NVARCHAR(500) NOT NULL,

    Description NVARCHAR(500) NULL,

    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),

    UpdatedAt DATETIME2 NULL
);